[package]
name = "engine"
version = "0.1.0"
authors = ["David <David>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
